### ISSUE TITLE
Can't run the package : Use of const in strict mode

### ISSUE THREAD

**Issue by Donovan-Ensicaen** [choonkending/react-webpack-node#143]
Hi guys,

The starter kit seems great but I can't run it. I have this error :

```
react-webpack-node-master/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (react-webpack-node-master/node_modules/connect-mongo/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/react-webpack-node-master/server/config/express.js:4:19)
    at Module._compile (module.js:460:26)
```

Do you have an idea about this error?
Thanks

**Comment by choonkending** [comment]
Thanks for raising this issue.


Just checking, did you run `npm install` and `npm run build`? Also which version of node are you running?
I'd need to get a bit more info because I'm not sure what the cause of this issue is. :)

**Comment by Donovan-Ensicaen** [comment]
I was using an old version of node...

You can close the issue.
Thanks @choonkending
