### ISSUE TITLE
3 tests failed on first test after npm install

### ISSUE THREAD

**Issue by sebkouba** [choonkending/react-webpack-node#179]
Hi Ken,
This project looks really interesting and it does exactly what I want to learn. I now want to dissect it to really understand it. The first problem I'm running into is that not all tests pass after I run npm test for the first time. Is there something I'm doing wrong or is that expected?
I'm running node v5.4.1
Thanks for your time.

```
FAILED TESTS:
  Topic Actions
    Asynchronous actions
      ✖ dispatches request and success actions when status is 200
        Node.js (darwin; U; rv:v5.4.1)
      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
          at callback (/Users/seb/dev/pg/pbt-react-webpack-node/node_modules/jsdom/lib/jsdom/browser/Window.js:432:19)
          at Timer.listOnTimeout (timers.js:92:15)

      ✖ dispatches request and failed actions when status is NOT 200
        Node.js (darwin; U; rv:v5.4.1)
      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
          at callback (/Users/seb/dev/pg/pbt-react-webpack-node/node_modules/jsdom/lib/jsdom/browser/Window.js:432:19)
          at Timer.listOnTimeout (timers.js:92:15)

      ✖ dispatches a duplicate action for a duplicate topic
        Node.js (darwin; U; rv:v5.4.1)
      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
          at callback (/Users/seb/dev/pg/pbt-react-webpack-node/node_modules/jsdom/lib/jsdom/browser/Window.js:432:19)
          at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by choonkending** [comment]
Hey mate, the recent change with update package dependencies and postcss
might have broken the test. I'll have a look!

**Comment by choonkending** [comment]
@sebkouba Thanks for raising this.

https://github.com/arnaudbenard/redux-mock-store -> recently gave a major version bump

**Comment by choonkending** [comment]
@sebkouba Fixed :+1: 

Pull and let me know how it goes.

**Comment by sebkouba** [comment]
That was fast! It works for me as well!
I'm impressed. I had assumed I was doing something wrong...
