### ISSUE TITLE
Login fails with "Error: Failed to serialize user into session"

### ISSUE THREAD

**Issue by guido4000** [choonkending/react-webpack-node#31]
Local login is not possible. Status changes to "Waiting ..." and stays there.
```
Succeeded connected to: mongodb://localhost/ReactWebpackNode
Error: Failed to serialize user into session
    at pass (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:277:19)
    at serialized (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:282:7)
    at /Users/main/Projects/fun/react/react-webpack-node/server/config/passport.js:12:5
    at pass (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:290:9)
    at Authenticator.serializeUser (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:295:5)
    at IncomingMessage.req.login.req.logIn (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/http/request.js:48:29)
    at /Users/main/Projects/fun/react/react-webpack-node/server/controllers/users.js:16:9
    at allFailed (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:87:18)
    at attempt (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:277:9)
    at Strategy.authenticate (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport-local/lib/strategy.js:75:17)
    at attempt (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at exports.postLogin (/Users/main/Projects/fun/react/react-webpack-node/server/controllers/users.js:21:5)
    at Layer.handle [as handle_request] (/Users/main/Projects/fun/react/react-webpack-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/main/Projects/fun/react/react-webpack-node/node_modules/express/lib/router/route.js:131:13)
```

**Comment by choonkending** [comment]
@guido4000 Thanks for letting us know! 

You're right, when you do it locally, the database throws an error because there are no values within the database, and it only fails on the server end with a vague response when the user does not exist :(. The example email and password was intended for the demo website.

I was thinking of improving the login/register flow. In the meantime, the backend has the endpoint, set up for registering check `controllers/users.js`, so if you wanted to "register" with mongoDB really quickly, you could do paste something like this in your browser console (while your server is running on localhost:3000):

```javascript
var http = new XMLHttpRequest();
var url = "http://localhost:3000/signup";
var params = "email=example@ninja.com&password=ninja";
http.open("POST", url, true);
http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
http.send(params);
```

This should create the values in your db, and you can then login with the credentials. Sorry for the confusion!

**Comment by guido4000** [comment]
Thank you for the feedback. I created this user, but still get a similar error.
```
> db.users.find()
{ "_id" : ObjectId("55900d6cdc6b64f21cd41256"), "email" : "example@ninja.com", "password" : "$2a$05$2ZWr5Ohq25R14v1JEfxnb.NbeByutq.GUW317oxpsqqGe0/HsfF0a", "profile" : { "picture" : "", "website" : "", "location" : "", "gender" : "", "name" : "" }, "tokens" : [ ], "__v" : 0 }
```

```
Succeeded connected to: mongodb://localhost/ReactWebpackNode
Error: Failed to serialize user into session
    at pass (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:277:19)
    at serialized (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:282:7)
    at /Users/main/Projects/fun/react/react-webpack-node/server/config/passport.js:12:5
    at pass (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:290:9)
    at Authenticator.serializeUser (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/authenticator.js:295:5)
    at IncomingMessage.req.login.req.logIn (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/http/request.js:48:29)
    at /Users/main/Projects/fun/react/react-webpack-node/server/controllers/users.js:16:9
    at allFailed (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:87:18)
    at attempt (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport/lib/middleware/authenticate.js:277:9)
    at verified (/Users/main/Projects/fun/react/react-webpack-node/node_modules/passport-local/lib/strategy.js:82:30)
    at /Users/main/Projects/fun/react/react-webpack-node/server/config/passport/local.js:18:22
    at /Users/main/Projects/fun/react/react-webpack-node/node_modules/mongoose/lib/query.js:1174:16
    at /Users/main/Projects/fun/react/react-webpack-node/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at process._tickCallback (node.js:355:11)
```

**Comment by choonkending** [comment]
Please reopen if still encountering this with the current version. This repo has undergone some serious changes since then :D
