### ISSUE TITLE
Error: Unhandled aborted transition! Reason: [object Object]

### ISSUE THREAD

**Issue by joshhornby** [choonkending/react-webpack-node#51]
As mentioned here https://github.com/choonkending/react-webpack-node/issues/50#issuecomment-129511751 I am having issues when trying to set up an authenticated route.

You can see [in the following code example](https://github.com/joshhornby/react-webpack-node/commit/a7701eaa7004c069c124ffe766da03baed7d942f) - if you try and visit the about route via the nav bar you will successfully see the login page such as `http://localhost:3000/login?nextPath=%2Fabout`

But if you go to `http://localhost:3000/about` directly the following error is shown:

```
Error: Unhandled aborted transition! Reason: [object Object]
   at Function.React.createClass.statics.handleAbort (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/createRouter.js:262:55)
   at Function.dispatchHandler (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/createRouter.js:379:20)
   at /Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/createRouter.js:349:29
   at /Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/Transition.js:64:41
   at /Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/Transition.js:69:9
   at Function.Transition.to (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/Transition.js:72:15)
   at /Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/createRouter.js:348:22
   at Function.Transition.from (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/Transition.js:51:15)
   at Function.dispatch (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/createRouter.js:345:20)
   at Function.refresh (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/createRouter.js:396:16)
   at Function.run (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/createRouter.js:392:16)
   at Object.runRouter [as run] (/Users/joshuahornby/code/react-webpack-node/node_modules/react-router/lib/runRouter.js:45:10)
   at renderToMarkup (/Users/joshuahornby/code/react-webpack-node/public/assets/app.server.js:132:29)
   at UniversalRenderer.render (/Users/joshuahornby/code/react-webpack-node/public/assets/app.server.js:155:23)
   at /Users/joshuahornby/code/react-webpack-node/server/config/routes.js:83:16
   at Layer.handle [as handle_request] (/Users/joshuahornby/code/react-webpack-node/node_modules/express/lib/router/layer.js:95:5)
```

After some discussion on [Reactiflux](http://www.reactiflux.com/) with @ericclemmons I believe the issue is due to the server render function and this package would fix this https://github.com/ericclemmons/react-router-server-location

I think updating the server function to call the `Router.create` function like https://github.com/ericclemmons/react-router-server-location/blob/master/test/support/express.js would fix the issue. Although not sure how this would work with Iso.

This would also help towards solving issue https://github.com/choonkending/react-webpack-node/issues/47 which I believe to be a big feature that should be added to this boilerplate.

**Comment by choonkending** [comment]
Thanks! I was trying the protected routes last night (on a branch I haven't
pushed up yet) and encountered the same error on refresh.

I'll have a look at react router server location. Thanks for that!

**Comment by joshhornby** [comment]
No worries @choonkending

After looking at using React Router server side I was most stuck on how to pass the local data through. 

Looking forward to seeing what you come up with :+1
