### ISSUE TITLE
npm run dev failing

### ISSUE THREAD

**Issue by rhys-edwards** [choonkending/react-webpack-node#63]
Can't seem to get this working.
I've ensured mongodb, mongoose are all installed. What am I missing?

````
rhysedwards$ npm run dev

> react-webpack-node@1.2.0 dev /Users/rhysedwards/Downloads/ideas
> NODE_ENV=development node server/index.js

Environment: development
Error connecting to: mongodb://localhost/ReactWebpackNode. MongoError: connect ECONNREFUSED

/Users/rhysedwards/Downloads/ideas/node_modules/connect-mongo/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@1.2.0 dev: `NODE_ENV=development node server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-webpack-node@1.2.0 dev script 'NODE_ENV=development node server/index.js'.
npm ERR! This is most likely a problem with the react-webpack-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node server/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-webpack-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rhysedwards/Downloads/ideas/npm-debug.log
````

**Comment by rhys-edwards** [comment]
Had an unrelated mongo installation issue. Closing this.

**Comment by abritez** [comment]
Having similar issue when deploying to Heroku. Any chance you remember what the issue was
